### ISSUE TITLE
Beginner question about frozen layers and transfer learning

### ISSUE THREAD

**Issue by emipasat** [FurkanOM/tf-faster-rcnn#1]
When training the RPN Model for example, wouldn't be more suitable to reuse the weights for 'imagenet' instead of retrain all model from scratch?
Did you noticed better results when training all model instead of only last layers?
Thank you

**Comment by FurkanOM** [comment]
Hi @emipasat,
1. The model is already using imagenet weights. You need to read about default params of keras applications, for [VGG16](https://www.tensorflow.org/api_docs/python/tf/keras/applications/VGG16).
2. The model is already working to train not only the last layers but all the layers.

**Comment by emipasat** [comment]
Sorry for not being clear. My question was if is worth to freeze the backbone layers and to train only the ones added by you, the last ones. 
Would it work that, too?
Thank you

**Comment by FurkanOM** [comment]
You could give it a try. However, in my experience, fine-tuning generally gives better results than transfer learning.
