### ISSUE TITLE
hello, it's too slow to download data by tfds.load

### ISSUE THREAD

**Issue by cmd23333** [FurkanOM/tf-faster-rcnn#2]
I have a voc2007 datasets, how to use it without tfds.load() ?
and it seems your code is wrong with it:
    data_utils.get_dataset("voc/2007", "train+validation")

voc2007 is in the tfds' list, voc/2007 not.

**Comment by FurkanOM** [comment]
Hi,
There are two version of voc dataset, voc/2007 and voc/2012.
You could read about the tfds versioning/configs for voc datasets from [here](https://www.tensorflow.org/datasets/catalog/voc#voc2007_default_config).
