### ISSUE TITLE
bouding boxes predictions on rpn

### ISSUE THREAD

**Issue by emipasat** [FurkanOM/tf-faster-rcnn#3]
Hi, I trained the RPN only with rpn_trainer.py with mobilenet_v2 backbone on voc2007, batch size 1 and 50 epochs.
But when running rpn_predictor.py as it is, no changes, I got tons of bounding boxes like in attached image. 
Which code should be run to get similar predictions (i.e. just a few bounding boxes) like you obtained in your example with the lion picture?
Thanks!
![image](https://user-images.githubusercontent.com/13704492/83377190-830d2c80-a3dd-11ea-8cfd-9646af8e5c28.png)
![image](https://user-images.githubusercontent.com/13704492/83377203-8accd100-a3dd-11ea-8f29-dc8a5cd3df7e.png)

**Comment by emipasat** [comment]
This is your example I was referring to (from the other repository):
![image](https://user-images.githubusercontent.com/13704492/83377261-bcde3300-a3dd-11ea-9d81-7dea0df840af.png)

**Comment by FurkanOM** [comment]
Hi, the lion prediction was made without the nms.
If you remove the non max suppression method, sort the predictions according to the probabilities and draw the first few results, you can get similar results.

**Comment by FurkanOM** [comment]
Or you can try my last update.
I made the change mentioned above in rpn predictor.

**Comment by emipasat** [comment]
With the latest update I got these (with a clean pulled master branch). All boxes are starting from upper left:
![image](https://user-images.githubusercontent.com/13704492/83478609-f1fe8a00-a49e-11ea-9730-abf86f09d1df.png)
![image](https://user-images.githubusercontent.com/13704492/83478621-f88d0180-a49e-11ea-9a6f-936549724cb0.png)
Doing a quick print of the selected_rpn_bboxes tensor gives values between 1 and 10:
![image](https://user-images.githubusercontent.com/13704492/83480472-26287980-a4a4-11ea-96f8-60c3605856e6.png)
From the TF docs it seems expected values should be between 0 and 1:
![image](https://user-images.githubusercontent.com/13704492/83480589-815a6c00-a4a4-11ea-9f39-617f122db561.png)

Should I try to retrain my model or I'm missing something? 
Model is trained with rpn_trainer.py, mobilenet_v2 and voc/2007.

**Comment by FurkanOM** [comment]
Hi, your results already range from 0 to 1.
We can simply say that your model is not well trained.
When your model is sufficiently trained, you should get similar results below.
![dog](https://user-images.githubusercontent.com/1816745/83501442-c8f2ef00-a4c8-11ea-9ced-41a10cae8b2f.png)
![people](https://user-images.githubusercontent.com/1816745/83501453-cc867600-a4c8-11ea-8fb6-74ad347f5491.png)

**Comment by emipasat** [comment]
Ok, I'll train it again for 100 epochs and for voc2012. 
Thanks a lot!
