### ISSUE TITLE
ValueError: Dimension 2 in both shapes must be equal, but are 4 and 1. Shapes are [?,1500,4] and [?,1500,1]. for 'roi_deltas/Select' (op: 'Select') with input shapes: [?,1500,1], [?,1500,4], [?,1500,4].

### ISSUE THREAD

**Issue by SeHwanJoo** [FurkanOM/tf-faster-rcnn#9]
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Traceback (most recent call last):
  File "C:/Users/famer/PycharmProjects/tf-faster-rcnn/faster_rcnn_trainer.py", line 53, in <module>
    frcnn_model = faster_rcnn.get_model(feature_extractor, rpn_model, anchors, hyper_params)
  File "C:\Users\famer\PycharmProjects\tf-faster-rcnn\models\faster_rcnn.py", line 254, in get_model
    [roi_bboxes, input_gt_boxes, input_gt_labels])
  File "C:\Users\famer\anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 854, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\Users\famer\anaconda3\lib\site-packages\tensorflow_core\python\autograph\impl\api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in converted code:
    relative to C:\Users\famer:

    PycharmProjects\tf-faster-rcnn\models\faster_rcnn.py:162 call  *
        expanded_gt_boxes = tf.where(tf.expand_dims(pos_mask, axis=-1), gt_boxes_map, tf.zeros_like(gt_boxes_map))
    anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py:324 new_func
        return func(*args, **kwargs)
    anaconda3\lib\site-packages\tensorflow_core\python\util\dispatch.py:180 wrapper
        return target(*args, **kwargs)
    anaconda3\lib\site-packages\tensorflow_core\python\ops\array_ops.py:3759 where
        return gen_math_ops.select(condition=condition, x=x, y=y, name=name)
    anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_math_ops.py:9439 select
        "Select", condition=condition, t=x, e=y, name=name)
    anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py:794 _apply_op_helper
        op_def=op_def)
    anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py:507 new_func
        return func(*args, **kwargs)
    anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:3357 create_op
        attrs, op_def, compute_device)
    anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:3426 _create_op_internal
        op_def=op_def)
    anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:1770 __init__
        control_input_ops)
    anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:1610 _create_c_op
        raise ValueError(str(e))

    ValueError: Dimension 2 in both shapes must be equal, but are 4 and 1. Shapes are [?,1500,4] and [?,1500,1]. for 'roi_deltas/Select' (op: 'Select') with input shapes: [?,1500,1], [?,1500,4], [?,1500,4].

tensorflow version : 2.0
python version : 3.7.6

I think this error occur at tf.where because update tensorflow

**Comment by prateeklath** [comment]
Hi can you share the solution
